### ISSUE TITLE
add reference to a trade

### ISSUE THREAD

**Issue by jorisbontje** [BlockchainSociety/TrustDavis#27]
select one from the 'potential references' list

buyer can activate them for the seller
seller can activate them for the buyer

ideally you'd select those with the minimum premium; until you have 100% insurance

**Comment by 0xc1c4da** [comment]
created the basic methods seem to be working, but i have issue with check();

check(peer, Peers.simpleSchema());
check(trade, Trades.simpleSchema());
both js objects look like they match the schema so i don't understand it's problem

**Comment by jorisbontje** [comment]
basic implementation is working.
